import React, {Component} from 'react';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Button from 'react-bootstrap/Button';
import Alert from 'react-bootstrap/Alert';
import Form from 'react-bootstrap/Form';
import Container from 'react-bootstrap/Container';
import logo from '../images/logo-hive.svg';
import InfoWhite from '../images/icons/information-white.svg';
// import {NavLink } from "react-router-dom";

var randomstring = require("randomstring");
var qr = require('qr-encode');
var secretKey = randomstring.generate({
  length: 16,
  charset: 'alphanumeric'
});
var dataURI = qr(secretKey, {type: 6, size: 6, level: 'M'});

class SignUpSixth extends Component {
  /* eslint-disable */
  continue = e => {
    e.preventDefault;
    this.props.nextStep();
  }

  back = e => {
    e.preventDefault;
    this.props.prevStep();
  }

  // constructor() {
  //   super()
  //   this.state = {
  //     walletName: '',
  //     password: ''
  //   }
  //
  //   this.onChange = this.onChange.bind(this)
  //   this.onSubmit = this.onSubmit.bind(this)
  // }
  //
  // onChange(e) {
  //   this.setState({[e.target.name]: e.target.value})
  // }
  //
  // onSubmit(e) { //TODO make it work
  //   e.preventDefault()
  //
  //   // const wallet = {
  //   //   walletName: this.state.walletName,
  //   //   password: this.state.password
  //   // }
  // }

  render() {
    return (
      <Container fluid className="h-100">
        <Row>
          <Col className="content loginsignup">
            <Row className="logoContainer">
              <Col sm={12}>
                <img src={logo} className="logoFront" alt="Hive logo"/>
              </Col>
            </Row>
            <Row>
              <Col sm={3} lg={4}></Col>
              <Col sm={6} lg={4}>
                <Alert variant="info">
                  <Row>
                    <Col className="d-flex align-items-center" sm={2}>
                      <img className="infoIcon" src={InfoWhite} alt="info"/>
                    </Col>

                    <Col sm={10}>
                      <Alert.Heading className="alertHeading" >Two Factor Authentication</Alert.Heading>
                      <p>Use your preferred 2FA application (eg. Google Authenticator, Authy) by scanning the QR code or enter the secret key manually into the app. Enter the 6 digit verification code generated by your app in the field below (NB: This is a demo, you can just press 'Next').</p>
                    </Col>
                  </Row>
                </Alert>
                <Row>
                  <Col sm={4}>
                    <img className="qrFromSeed" src={dataURI} alt="qr-from-seed" style={{width:"100%", margin:"0 auto", border:"10px solid white"}}/>
                  </Col>
                  <Col sm={8}>
                    <Form noValidate>
                      <Form.Group className="formTemplate" controlId="form2FA">
                        <Form.Control type="text" readOnly defaultValue={secretKey} />
                        <Form.Control type="text" placeholder="Enter Verification Code" />
                      </Form.Group>
                    </Form>
                  </Col>
                </Row>
              </Col>
              <Col sm={3} lg={4}></Col>
            </Row>
            <Row className="colsButtons" style={{marginTop:"1em"}}>
              <Col sm={3} lg={4}></Col>
              <Col sm={6} lg={4}>
              <Row className="">
                <Col sm={6}>
                  <Button block
                    variant="outline-primary"
                    onClick={this.back}>Back
                  </Button>
                </Col>

                <Col sm={6}>
                  <Button block
                    variant="primary"
                    onClick={this.continue}>Next
                  </Button>
                </Col>
              </Row>
              </Col>
              <Col sm={3} lg={4}></Col>
            </Row>
          </Col>
        </Row>
      </Container>
    )
  }
}

export default SignUpSixth;
